const dict = {
  en: {
    prototype_notice:'Pilot environment · all prices and transactions shown are simulated', corridor_notice:'Bogra–Dhaka corridor prototype',
    brand_sub:'Agricultural markets, connected.', nav_overview:'Overview', nav_markets:'Markets', nav_sell:'Post supply', nav_demand:'Buyer demand', nav_matches:'Matches', nav_intelligence:'Intelligence', operations:'OPERATIONS', nav_trades:'Trades', nav_logistics:'Logistics', nav_quality:'Quality & QC', pilot_label:'PILOT MARKET', pilot_route:'Bogra → Dhaka', pilot_desc:'Potato, onion and rice market simulation.', pilot_stage:'Product design · Stage 1', help:'Help & documentation', search_placeholder:'Search commodity, market or buyer', demo_account:'Demo account', operator_role:'Platform operator', market_pulse:'MARKET PULSE', simulated_label:'SIMULATED',
    workspace_label:'AGRO-EXCHANGE WORKSPACE', overview_title:'Market overview', overview_sub:'Price discovery, active demand and trade opportunities across the pilot corridor.', post_demand:'Post demand', post_supply:'Post supply', metric_supply:'Listed supply', metric_supply_note:'across 6 active listings', metric_demand:'Open buyer demand', metric_demand_note:'across 3 verified buyers', metric_match:'Match rate', metric_match_note:'eligible orders matched', metric_completion:'Completion rate', metric_completion_note:'accepted matches completed',
    live_markets:'Live market board', live_markets_sub:'Indicative pilot market conditions', view_all:'View all →', th_market:'Market', th_last:'Last trade', th_change:'7d', th_supply:'Supply', th_demand:'Demand', th_delivered:'Dhaka delivered', th_signal:'Signal', all_commodities:'All commodities',
    best_opportunity_label:'BEST CURRENT OPPORTUNITY', best_opportunity:'Bogra potato → Dhaka', modelled:'Modelled', net_spread:'Net spatial spread', after_costs:'after indicative fulfilment costs', farmgate:'Farmgate', fulfilment:'Collection + QC + transport', buyer_bid:'Buyer bid', review_match:'Review matching opportunities', opportunity_note:'This is a simulated opportunity, not a live recommendation.',
    recent_trades:'Recent verified trades', recent_trades_sub:'Transaction trail for the pilot simulation', settled_status:'4 settled', th_trade:'Trade', th_route:'Route', th_qty:'Qty', th_price:'Farmgate', th_status:'Status', market_intelligence:'Market intelligence', market_intelligence_sub:'Signals derived from pilot data', tightest_market:'Tightest market', onion_bogra:'Bogra onion', demand_supply_ratio:'demand/supply', lowest_delivered:'Lowest delivered potato', from_bogra:'From Bogra', fastest_match:'Fastest recent match', potato_bogra_dhaka:'Potato, Bogra → Dhaka',
    market_intelligence_label:'MARKET INTELLIGENCE', markets_title:'Markets', markets_sub:'Compare source-market prices, supply, demand and indicative delivered costs.', export_data:'Export data', commodity:'Commodity', origin:'Origin', search_market:'Search market', market_search_placeholder:'e.g. potato or Bogra', all_origins:'All origins', th_commodity:'Commodity', th_origin:'Origin', th_ask:'Asking range',
    new_listing_label:'NEW LISTING', sell_title:'Post supply', sell_sub:'Create a supply listing and compare it with current buyer demand before publishing.', produce_details:'Produce details', produce_details_sub:'What are you offering to the market?', grade:'Quality / grade', quantity_kg:'Quantity (kg)', minimum_price:'Minimum price (Tk/kg)', available_date:'Available date', listing_preferences:'Listing preferences', listing_preferences_sub:'The matching engine will use these constraints.', collection_base:'Deliver to collection point', collection_base_sub:'Preferred for pilot matching', farm_pickup:'Request farm pickup', farm_pickup_sub:'Subject to route capacity', save_draft:'Save draft', find_buyers:'Find compatible buyers', market_context:'MARKET CONTEXT', potato_bogra_title:'Potato · Bogra', last_verified_trade:'Last simulated verified trade', asking_range:'Asking range', buyer_demand_today:'Buyer demand', dhaka_delivery_cost:'Dhaka fulfilment', why_this_matters:'Why this matters', seller_note:'A seller should see credible alternatives and delivered economics before accepting an offer, not just a headline market price.',
    verified_buyers_label:'VERIFIED BUYERS', demand_title:'Buyer demand', demand_sub:'Open procurement requirements from wholesalers, distributors and processors.', matching_engine_label:'MATCHING ENGINE', matches_title:'Ranked opportunities', matches_sub:'Feasible matches ranked by delivered economics, quantity fit, timing and counterparty reliability.', decision_support_label:'DECISION SUPPORT', intelligence_title:'Market intelligence', intelligence_sub:'Turn transaction and route data into signals that buyers, sellers and institutions can use.', price_dispersion:'Regional price dispersion', potato_reference:'Potato · simulated farmgate reference', liquidity_quality:'Market liquidity', liquidity_quality_sub:'Pilot transaction quality', match_rate:'Match rate', completion_rate:'Completion rate', repeat_buyers:'Repeat buyers', corridor_economics:'Bogra → Dhaka corridor economics', corridor_economics_sub:'Illustrative delivered-cost decomposition for potato', collection_qc:'Collection + QC', transport:'Transport', delivered_cost:'Delivered cost', footer_note:'Prototype only · simulated data · no payments or binding contracts',
    signal_tight:'Tight', signal_balanced:'Balanced', signal_surplus:'Surplus', settled:'Settled', verified:'Verified', required:'Required', destination:'Destination', target_price:'Target price', delivery:'Delivery', review_demand:'Review demand', match_score:'Match score', delivered_economics:'Delivered economics', quantity:'Quantity', timing:'Timing', review:'Review match', tomorrow:'Tomorrow', two_days:'2 days', three_days:'3 days', wholesaler:'Wholesaler', distributor:'Retail distributor', processor:'Processor', prototype_toast:'This control is included for interface testing and will be activated in a later build.', found_matches:'Three compatible buyer matches found.'
  },
  bn: {
    prototype_notice:'পাইলট পরিবেশ · প্রদর্শিত সব মূল্য ও লেনদেন সিমুলেটেড', corridor_notice:'বগুড়া–ঢাকা করিডর প্রোটোটাইপ',
    brand_sub:'কৃষি বাজার, একই নেটওয়ার্কে।', nav_overview:'সারসংক্ষেপ', nav_markets:'বাজার', nav_sell:'সরবরাহ পোস্ট', nav_demand:'ক্রেতার চাহিদা', nav_matches:'ম্যাচ', nav_intelligence:'বাজার বিশ্লেষণ', operations:'অপারেশন', nav_trades:'লেনদেন', nav_logistics:'লজিস্টিকস', nav_quality:'মান ও QC', pilot_label:'পাইলট বাজার', pilot_route:'বগুড়া → ঢাকা', pilot_desc:'আলু, পেঁয়াজ ও চালের বাজার সিমুলেশন।', pilot_stage:'পণ্য নকশা · ধাপ ১', help:'সহায়তা ও নির্দেশিকা', search_placeholder:'পণ্য, বাজার বা ক্রেতা খুঁজুন', demo_account:'ডেমো অ্যাকাউন্ট', operator_role:'প্ল্যাটফর্ম অপারেটর', market_pulse:'বাজারের পালস', simulated_label:'সিমুলেটেড',
    workspace_label:'অ্যাগ্রো-এক্সচেঞ্জ ওয়ার্কস্পেস', overview_title:'বাজারের সারসংক্ষেপ', overview_sub:'পাইলট করিডরে মূল্য, সক্রিয় চাহিদা ও সম্ভাব্য লেনদেন একসঙ্গে দেখুন।', post_demand:'চাহিদা পোস্ট', post_supply:'সরবরাহ পোস্ট', metric_supply:'তালিকাভুক্ত সরবরাহ', metric_supply_note:'৬টি সক্রিয় তালিকায়', metric_demand:'খোলা ক্রেতা চাহিদা', metric_demand_note:'৩ জন যাচাইকৃত ক্রেতা', metric_match:'ম্যাচ হার', metric_match_note:'যোগ্য অর্ডারের ম্যাচ', metric_completion:'সম্পন্নের হার', metric_completion_note:'গৃহীত ম্যাচ সম্পন্ন',
    live_markets:'লাইভ বাজার বোর্ড', live_markets_sub:'পাইলট বাজারের নির্দেশক অবস্থা', view_all:'সব দেখুন →', th_market:'বাজার', th_last:'শেষ লেনদেন', th_change:'৭ দিন', th_supply:'সরবরাহ', th_demand:'চাহিদা', th_delivered:'ঢাকায় পৌঁছানো', th_signal:'সংকেত', all_commodities:'সব পণ্য',
    best_opportunity_label:'বর্তমান সেরা সুযোগ', best_opportunity:'বগুড়ার আলু → ঢাকা', modelled:'মডেলভিত্তিক', net_spread:'নিট ভৌগোলিক ব্যবধান', after_costs:'আনুমানিক পূরণ খরচের পর', farmgate:'খামারদর', fulfilment:'সংগ্রহ + মান যাচাই + পরিবহন', buyer_bid:'ক্রেতার দর', review_match:'ম্যাচিং সুযোগ দেখুন', opportunity_note:'এটি সিমুলেটেড সুযোগ, লাইভ সুপারিশ নয়।',
    recent_trades:'সাম্প্রতিক যাচাইকৃত লেনদেন', recent_trades_sub:'পাইলট সিমুলেশনের লেনদেন রেকর্ড', settled_status:'৪টি নিষ্পত্তি', th_trade:'লেনদেন', th_route:'রুট', th_qty:'পরিমাণ', th_price:'খামারদর', th_status:'অবস্থা', market_intelligence:'বাজার বিশ্লেষণ', market_intelligence_sub:'পাইলট তথ্য থেকে প্রাপ্ত সংকেত', tightest_market:'সবচেয়ে টাইট বাজার', onion_bogra:'বগুড়ার পেঁয়াজ', demand_supply_ratio:'চাহিদা/সরবরাহ', lowest_delivered:'সর্বনিম্ন পৌঁছানো আলু', from_bogra:'বগুড়া থেকে', fastest_match:'দ্রুততম সাম্প্রতিক ম্যাচ', potato_bogra_dhaka:'আলু, বগুড়া → ঢাকা',
    market_intelligence_label:'বাজার তথ্য', markets_title:'বাজার', markets_sub:'উৎসবাজারের মূল্য, সরবরাহ, চাহিদা ও আনুমানিক পৌঁছানো খরচ তুলনা করুন।', export_data:'ডেটা এক্সপোর্ট', commodity:'পণ্য', origin:'উৎপত্তিস্থল', search_market:'বাজার খুঁজুন', market_search_placeholder:'যেমন আলু বা বগুড়া', all_origins:'সব উৎপত্তিস্থল', th_commodity:'পণ্য', th_origin:'উৎপত্তিস্থল', th_ask:'প্রস্তাবিত মূল্য',
    new_listing_label:'নতুন তালিকা', sell_title:'সরবরাহ পোস্ট করুন', sell_sub:'প্রকাশের আগে সরবরাহ তালিকা তৈরি করে বর্তমান ক্রেতা চাহিদার সঙ্গে তুলনা করুন।', produce_details:'পণ্যের তথ্য', produce_details_sub:'আপনি বাজারে কী দিতে চান?', grade:'মান / গ্রেড', quantity_kg:'পরিমাণ (কেজি)', minimum_price:'সর্বনিম্ন মূল্য (টাকা/কেজি)', available_date:'উপলব্ধ তারিখ', listing_preferences:'তালিকার পছন্দ', listing_preferences_sub:'ম্যাচিং ইঞ্জিন এই শর্তগুলো ব্যবহার করবে।', collection_base:'সংগ্রহ কেন্দ্রে পৌঁছে দিন', collection_base_sub:'পাইলট ম্যাচিংয়ের জন্য অগ্রাধিকার', farm_pickup:'খামার থেকে সংগ্রহ', farm_pickup_sub:'রুট সক্ষমতার ওপর নির্ভরশীল', save_draft:'খসড়া সংরক্ষণ', find_buyers:'উপযুক্ত ক্রেতা খুঁজুন', market_context:'বাজার প্রেক্ষাপট', potato_bogra_title:'আলু · বগুড়া', last_verified_trade:'শেষ সিমুলেটেড যাচাইকৃত লেনদেন', asking_range:'প্রস্তাবিত মূল্য', buyer_demand_today:'ক্রেতা চাহিদা', dhaka_delivery_cost:'ঢাকা পর্যন্ত পূরণ খরচ', why_this_matters:'কেন এটি গুরুত্বপূর্ণ', seller_note:'প্রস্তাব গ্রহণের আগে বিক্রেতার বিশ্বাসযোগ্য বিকল্প ও পৌঁছানো খরচ দেখা উচিত, শুধু একটি বাজারদর নয়।',
    verified_buyers_label:'যাচাইকৃত ক্রেতা', demand_title:'ক্রেতার চাহিদা', demand_sub:'পাইকার, পরিবেশক ও প্রক্রিয়াজাতকারীর খোলা ক্রয় চাহিদা।', matching_engine_label:'ম্যাচিং ইঞ্জিন', matches_title:'অগ্রাধিকারভিত্তিক সুযোগ', matches_sub:'পৌঁছানো অর্থনীতি, পরিমাণ, সময় ও পক্ষের নির্ভরযোগ্যতার ভিত্তিতে সম্ভাব্য ম্যাচ।', decision_support_label:'সিদ্ধান্ত সহায়তা', intelligence_title:'বাজার বিশ্লেষণ', intelligence_sub:'লেনদেন ও রুটের তথ্যকে বিক্রেতা, ক্রেতা ও প্রতিষ্ঠানের ব্যবহারযোগ্য সংকেতে রূপান্তর করুন।', price_dispersion:'আঞ্চলিক মূল্য বিচ্যুতি', potato_reference:'আলু · সিমুলেটেড খামারদর রেফারেন্স', liquidity_quality:'বাজারের তারল্য', liquidity_quality_sub:'পাইলট লেনদেনের মান', match_rate:'ম্যাচ হার', completion_rate:'সম্পন্নের হার', repeat_buyers:'পুনরায় আসা ক্রেতা', corridor_economics:'বগুড়া → ঢাকা করিডর অর্থনীতি', corridor_economics_sub:'আলুর উদাহরণমূলক পৌঁছানো খরচ', collection_qc:'সংগ্রহ + মান যাচাই', transport:'পরিবহন', delivered_cost:'পৌঁছানো খরচ', footer_note:'শুধু প্রোটোটাইপ · সিমুলেটেড তথ্য · কোনো পেমেন্ট বা বাধ্যতামূলক চুক্তি নয়',
    signal_tight:'টাইট', signal_balanced:'ভারসাম্য', signal_surplus:'উদ্বৃত্ত', settled:'নিষ্পত্তি', verified:'যাচাইকৃত', required:'প্রয়োজন', destination:'গন্তব্য', target_price:'লক্ষ্যমূল্য', delivery:'ডেলিভারি', review_demand:'চাহিদা দেখুন', match_score:'ম্যাচ স্কোর', delivered_economics:'পৌঁছানো অর্থনীতি', quantity:'পরিমাণ', timing:'সময়', review:'ম্যাচ দেখুন', tomorrow:'আগামীকাল', two_days:'২ দিন', three_days:'৩ দিন', wholesaler:'পাইকার', distributor:'খুচরা পরিবেশক', processor:'প্রক্রিয়াজাতকারী', prototype_toast:'এই কন্ট্রোলটি ইন্টারফেস পরীক্ষার জন্য রাখা হয়েছে এবং পরবর্তী সংস্করণে সক্রিয় হবে।', found_matches:'তিনটি উপযুক্ত ক্রেতা ম্যাচ পাওয়া গেছে।'
  }
};

const placeBn={Bogra:'বগুড়া',Rangpur:'রংপুর',Joypurhat:'জয়পুরহাট',Dhaka:'ঢাকা',Gazipur:'গাজীপুর'};
const commodityBn={Potato:'আলু',Onion:'পেঁয়াজ',Rice:'চাল'};
const markets=[
  {commodity:'Potato',origin:'Bogra',price:29.2,change:4.2,supply:84,demand:61,ask:'28–32',delivered:32.7,signal:'surplus'},
  {commodity:'Potato',origin:'Rangpur',price:27.8,change:2.8,supply:53,demand:44,ask:'27–30',delivered:33.8,signal:'balanced'},
  {commodity:'Onion',origin:'Bogra',price:46.5,change:6.1,supply:25,demand:52,ask:'44–48',delivered:51.6,signal:'tight'},
  {commodity:'Onion',origin:'Joypurhat',price:45.8,change:4.9,supply:18,demand:39,ask:'44–47',delivered:51.0,signal:'tight'},
  {commodity:'Rice',origin:'Bogra',price:58.4,change:1.2,supply:112,demand:96,ask:'57–60',delivered:61.1,signal:'balanced'},
  {commodity:'Rice',origin:'Rangpur',price:57.2,change:0.6,supply:91,demand:88,ask:'56–59',delivered:61.0,signal:'balanced'}
];
const trades=[
  {commodity:'Potato',route:['Bogra','Dhaka'],qty:'2.4 t',farmgate:'Tk 30.1',status:'settled'},
  {commodity:'Onion',route:['Joypurhat','Dhaka'],qty:'1.2 t',farmgate:'Tk 46.0',status:'settled'},
  {commodity:'Rice',route:['Rangpur','Gazipur'],qty:'4.8 t',farmgate:'Tk 57.6',status:'settled'},
  {commodity:'Potato',route:['Rangpur','Dhaka'],qty:'3.1 t',farmgate:'Tk 28.2',status:'settled'}
];
const buyers=[
  {initials:'DF',name:'Dhaka Fresh Traders',type:'wholesaler',commodity:'Potato',qty:'12 t',destination:'Dhaka',price:'Tk 37.5/kg',delivery:'tomorrow'},
  {initials:'MR',name:'Metro Retail Supply',type:'distributor',commodity:'Onion',qty:'8 t',destination:'Dhaka',price:'Tk 55.0/kg',delivery:'two_days'},
  {initials:'GF',name:'Gazipur Foods Ltd.',type:'processor',commodity:'Rice',qty:'25 t',destination:'Gazipur',price:'Tk 63.0/kg',delivery:'three_days'}
];
const matches=[
  {origin:'Bogra',commodity:'Potato',grade:'A',buyer:'Dhaka Fresh Traders',score:92,economics:'Tk 32.7 → 37.5',qty:'12 t',timing:'tomorrow'},
  {origin:'Rangpur',commodity:'Potato',grade:'A',buyer:'Dhaka Fresh Traders',score:86,economics:'Tk 33.8 → 37.5',qty:'10 t',timing:'tomorrow'},
  {origin:'Joypurhat',commodity:'Onion',grade:'A',buyer:'Metro Retail Supply',score:89,economics:'Tk 51.0 → 55.0',qty:'8 t',timing:'two_days'}
];
let lang='en';
const t=k=>dict[lang][k]||k;
const c=x=>lang==='bn'?(commodityBn[x]||x):x;
const p=x=>lang==='bn'?(placeBn[x]||x):x;
const route=r=>r.map(p).join(' → ');
const signalLabel=s=>t(`signal_${s}`);

function renderTicker(){const subset=[markets[0],markets[2],markets[4],markets[1]];document.getElementById('tickerItems').innerHTML=subset.map(m=>`<div class="ticker-item"><strong>${c(m.commodity)} · ${p(m.origin)}</strong><span>Tk ${m.price.toFixed(1)}</span><span class="${m.change>=0?'up':'down'}">${m.change>=0?'↑':'↓'} ${Math.abs(m.change).toFixed(1)}%</span></div>`).join('')}
function marketRow(m,full=false){const market=full?`<td><strong>${c(m.commodity)}</strong></td><td>${p(m.origin)}</td>`:`<td><div class="market-cell"><div class="commodity-icon">${c(m.commodity).slice(0,2)}</div><div><strong>${c(m.commodity)}</strong><span>${p(m.origin)}</span></div></div></td>`;return `<tr>${market}<td class="price-cell">Tk ${m.price.toFixed(1)}</td><td class="change-up">↑ ${m.change.toFixed(1)}%</td>${full?`<td>Tk ${m.ask}</td>`:''}<td>${m.supply} t</td><td>${m.demand} t</td><td class="price-cell">Tk ${m.delivered.toFixed(1)}</td><td><span class="signal ${m.signal}">${signalLabel(m.signal)}</span></td></tr>`}
function renderOverviewMarkets(){const filter=document.getElementById('overviewCommodityFilter').value;const rows=markets.filter(m=>filter==='all'||m.commodity===filter).slice(0,5);document.getElementById('overviewMarketTable').innerHTML=rows.map(m=>marketRow(m,false)).join('')}
function renderFullMarkets(){const commodity=document.getElementById('marketCommodityFilter').value;const origin=document.getElementById('marketOriginFilter').value;const q=document.getElementById('marketSearch').value.trim().toLowerCase();const rows=markets.filter(m=>(commodity==='all'||m.commodity===commodity)&&(origin==='all'||m.origin===origin)&&(!q||m.commodity.toLowerCase().includes(q)||m.origin.toLowerCase().includes(q)||(commodityBn[m.commodity]||'').includes(q)||(placeBn[m.origin]||'').includes(q)));document.getElementById('fullMarketTable').innerHTML=rows.map(m=>marketRow(m,true)).join('')}
function renderTrades(){document.getElementById('recentTradesTable').innerHTML=trades.map(x=>`<tr><td><strong>${c(x.commodity)}</strong></td><td>${route(x.route)}</td><td>${x.qty}</td><td class="price-cell">${x.farmgate}</td><td><span class="signal surplus">✓ ${t('settled')}</span></td></tr>`).join('')}
function renderBuyers(){document.getElementById('buyerDemandGrid').innerHTML=buyers.map(b=>`<article class="card buyer-card"><div class="buyer-card-head"><div class="buyer-logo">${b.initials}</div><div class="buyer-title"><strong>${b.name}</strong><span>${t(b.type)}</span></div><span class="verified-check">✓ ${t('verified')}</span></div><div class="buyer-main">${c(b.commodity)} <span>· ${b.qty}</span></div><div class="buyer-details"><div class="buyer-detail"><span>${t('destination')}</span><strong>${p(b.destination)}</strong></div><div class="buyer-detail"><span>${t('target_price')}</span><strong>${b.price}</strong></div><div class="buyer-detail"><span>${t('delivery')}</span><strong>${t(b.delivery)}</strong></div><div class="buyer-detail"><span>${t('required')}</span><strong>${b.qty}</strong></div></div><button class="button secondary prototype-action">${t('review_demand')}</button></article>`).join('');bindPrototypeActions()}
function renderMatches(){document.getElementById('matchList').innerHTML=matches.map(m=>`<article class="match-row"><div class="match-route"><strong>${p(m.origin)} · ${c(m.commodity)} · Grade ${m.grade}</strong><span>→ ${m.buyer}</span></div><div class="match-stat"><span>${t('match_score')}</span><strong class="score-value">${m.score}%</strong></div><div class="match-stat"><span>${t('delivered_economics')}</span><strong>${m.economics}</strong></div><div class="match-stat"><span>${t('quantity')}</span><strong>${m.qty}</strong></div><div class="match-stat"><span>${t('timing')}</span><strong>${t(m.timing)}</strong></div><button class="button secondary prototype-action">${t('review')}</button></article>`).join('');bindPrototypeActions()}
function renderPriceBars(){const vals=[['Bogra',29.2,76],['Rangpur',27.8,68],['Joypurhat',28.4,71],['Dhaka',37.5,96]];document.getElementById('priceBars').innerHTML=vals.map(([place,price,width])=>`<div class="bar-row"><span>${p(place)}</span><div class="bar-track"><div class="bar-fill" style="width:${width}%"></div></div><strong>Tk ${price}</strong></div>`).join('')}
function applyLanguage(){document.documentElement.lang=lang==='bn'?'bn':'en';document.querySelectorAll('[data-i18n]').forEach(el=>el.textContent=t(el.dataset.i18n));document.querySelectorAll('[data-i18n-placeholder]').forEach(el=>el.placeholder=t(el.dataset.i18nPlaceholder));document.querySelectorAll('[data-i18n-option]').forEach(el=>el.textContent=t(el.dataset.i18nOption));document.getElementById('langToggle').textContent=lang==='en'?'বাংলা':'English';renderTicker();renderOverviewMarkets();renderFullMarkets();renderTrades();renderBuyers();renderMatches();renderPriceBars()}
function showView(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));const target=document.getElementById(id);if(target)target.classList.add('active-view');document.querySelectorAll('.side-link[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===id));window.scrollTo({top:0,behavior:'smooth'});closeMobileMenu()}
function toast(msg){const el=document.getElementById('toast');el.textContent=msg;el.classList.add('show');clearTimeout(window.__toast);window.__toast=setTimeout(()=>el.classList.remove('show'),2300)}
function bindPrototypeActions(){document.querySelectorAll('.prototype-action').forEach(btn=>btn.onclick=()=>toast(t('prototype_toast')))}
function closeMobileMenu(){document.querySelector('.sidebar').classList.remove('open');document.getElementById('mobileOverlay').classList.remove('show')}

document.querySelectorAll('.side-link[data-view]').forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.view)));
document.querySelectorAll('[data-view-jump]').forEach(btn=>btn.addEventListener('click',()=>showView(btn.dataset.viewJump)));
document.querySelectorAll('[data-action="prototype"]').forEach(btn=>btn.addEventListener('click',()=>toast(t('prototype_toast'))));
document.getElementById('langToggle').addEventListener('click',()=>{lang=lang==='en'?'bn':'en';applyLanguage()});
document.getElementById('overviewCommodityFilter').addEventListener('change',renderOverviewMarkets);
document.getElementById('marketCommodityFilter').addEventListener('change',renderFullMarkets);
document.getElementById('marketOriginFilter').addEventListener('change',renderFullMarkets);
document.getElementById('marketSearch').addEventListener('input',renderFullMarkets);
document.getElementById('globalSearch').addEventListener('keydown',e=>{if(e.key==='Enter'){const q=e.target.value.toLowerCase();if(['potato','onion','rice','আলু','পেঁয়াজ','চাল','bogra','rangpur','joypurhat','বগুড়া','রংপুর','জয়পুরহাট'].some(x=>q.includes(x))){showView('markets');document.getElementById('marketSearch').value=e.target.value;renderFullMarkets()}else toast(t('prototype_toast'))}});
document.getElementById('sellForm').addEventListener('submit',e=>{e.preventDefault();showView('matches');toast(t('found_matches'))});
document.querySelectorAll('.choice-card').forEach(card=>card.addEventListener('click',()=>{document.querySelectorAll('.choice-card').forEach(x=>x.classList.remove('selected'));card.classList.add('selected')}));
document.getElementById('mobileMenu').addEventListener('click',()=>{document.querySelector('.sidebar').classList.add('open');document.getElementById('mobileOverlay').classList.add('show')});
document.getElementById('mobileOverlay').addEventListener('click',closeMobileMenu);
const tomorrow=new Date();tomorrow.setDate(tomorrow.getDate()+1);document.querySelector('input[type="date"]').value=tomorrow.toISOString().slice(0,10);applyLanguage();
